export const masterData = {
  status: [
    'CV Sent',
    'Interview',
    'Hold',
    'Offer Accepted',
    'Onboarded',
    'Interview Fail',
    'Offer Rejected',
    'CV Fail',
    'Searching',
    'Withdraw',
    'No-show',
    'Offered',
    'Offer',
  ],
  source: [
    'LinkedIn Job Post',
    'LinkedIn Search',
    'Vietnamworks Job Post',
    'Vietnamworks Search',
    'TopCV Job Post',
    'TopCV Search',
    'Facebook',
    'Internal Referral',
    'Headhunt',
    'Network',
    'Others',
  ],
  eeLevel: ['Intern', 'Operator', 'Technician', 'Engineer', 'Professional', 'Supervisor', 'Manager', 'Leader'],
  headhuntAgency: ['AsiaHr', 'Navigos', 'Adecco', 'Manpower', 'Persol', 'Talentrader', 'Prosworks'],
  department: ['AS', 'QC', 'HR', 'LOG', 'PUR', 'IT', 'FIN', 'MFG', 'ENG'],
  dlIdl: ['DL', 'IDL'],
};

export const pipelineStatuses = {
  cvSent: ['CV Sent'],
  interview: ['Interview'],
  offered: ['Offered', 'Offer'],
  offerAccepted: ['Offer Accepted'],
  onboarded: ['Onboarded'],
  offerRejected: ['Offer Rejected'],
};

export const mockJobs = [
  {
    id: 'job-001',
    jobCode: 'IDL-HR-001',
    project: 'Molex Expansion',
    department: 'HR',
    hcRequested: 2,
    jobTitle: 'HR Specialist',
    eeLevel: 'Professional',
    sites: 'Hanoi',
    projectSegment: 'Operations Excellence',
    hiringManager: 'Nguyen Minh Anh',
    hrbp: 'Pham Thu Ha',
    recruiter: 'Tran Lan',
    myhrRequestDate: '2026-05-02',
    expectedOnboardDate: '2026-07-01',
    status: 'Interview',
    source: 'LinkedIn Search',
    candidateName: '',
    onboardDate: '',
    offerDate: '',
    note: 'Priority role for new production line support.',
  },
  {
    id: 'job-002',
    jobCode: 'IDL-QC-002',
    project: 'Quality Ramp-up',
    department: 'QC',
    hcRequested: 3,
    jobTitle: 'Quality Engineer',
    eeLevel: 'Engineer',
    sites: 'Hanoi',
    projectSegment: 'Quality',
    hiringManager: 'Le Quang Huy',
    hrbp: 'Pham Thu Ha',
    recruiter: 'Tran Lan',
    myhrRequestDate: '2026-05-05',
    expectedOnboardDate: '2026-07-15',
    status: 'Offered',
    source: 'Vietnamworks Search',
    candidateName: 'Le Hoang C',
    onboardDate: '',
    offerDate: '2026-06-04',
    note: 'Need candidates with manufacturing QC background.',
  },
  {
    id: 'job-003',
    jobCode: 'IDL-LOG-003',
    project: 'Warehouse Optimization',
    department: 'LOG',
    hcRequested: 1,
    jobTitle: 'Logistics Supervisor',
    eeLevel: 'Supervisor',
    sites: 'Hanoi',
    projectSegment: 'Supply Chain',
    hiringManager: 'Do Thanh Son',
    hrbp: 'Bui Hoang Yen',
    recruiter: 'Nguyen Thuy',
    myhrRequestDate: '2026-05-20',
    expectedOnboardDate: '2026-08-01',
    status: 'Searching',
    source: 'Headhunt',
    candidateName: '',
    onboardDate: '',
    offerDate: '',
    note: 'Search via agency if no suitable direct applicants.',
  },
  {
    id: 'job-004',
    jobCode: 'IDL-AS-004',
    project: 'Automation Support',
    department: 'AS',
    hcRequested: 2,
    jobTitle: 'Automation Technician',
    eeLevel: 'Technician',
    sites: 'Hanoi',
    projectSegment: 'Automation',
    hiringManager: 'Vu Duc Long',
    hrbp: 'Pham Thu Ha',
    recruiter: 'Tran Lan',
    myhrRequestDate: '2026-05-28',
    expectedOnboardDate: '2026-08-10',
    status: 'CV Sent',
    source: 'TopCV Job Post',
    candidateName: '',
    onboardDate: '',
    offerDate: '',
    note: 'Focus on PLC / maintenance experience.',
  },
];

export const mockCandidates = [
  {
    id: 'cand-001',
    inputDate: '2026-05-15',
    department: 'HR',
    name: 'Nguyen Van A',
    email: 'a.nguyen@email.com',
    phone: '0912345678',
    recruiter: 'Tran Lan',
    jobCode: 'IDL-HR-001',
    jobTitle: 'HR Specialist',
    eeLevel: 'Professional',
    project: 'Molex Expansion',
    hiringManager: 'Nguyen Minh Anh',
    dlIdl: 'IDL',
    status: 'CV Sent',
    onboardingDate: '',
    offerSentDate: '',
    source: 'LinkedIn Search',
    employeeId: '',
    referrerName: '',
    referrerDepartment: '',
    note: 'Good HR operations background.',
    currentSalary: 18,
    expectedSalary: 24,
    candidateResultFeedbackDate: '',
    headhuntAgency: '',
    targetedCompany: false,
    targetedCompanyName: '',
  },
  {
    id: 'cand-002',
    inputDate: '2026-05-18',
    department: 'HR',
    name: 'Tran Thi B',
    email: 'b.tran@email.com',
    phone: '0987654321',
    recruiter: 'Tran Lan',
    jobCode: 'IDL-HR-001',
    jobTitle: 'HR Specialist',
    eeLevel: 'Professional',
    project: 'Molex Expansion',
    hiringManager: 'Nguyen Minh Anh',
    dlIdl: 'IDL',
    status: 'Interview',
    onboardingDate: '',
    offerSentDate: '',
    source: 'Internal Referral',
    employeeId: '',
    referrerName: 'Pham Hoang Dung',
    referrerDepartment: 'HR',
    note: 'Interview scheduled with hiring manager.',
    currentSalary: 20,
    expectedSalary: 27,
    candidateResultFeedbackDate: '2026-06-05',
    headhuntAgency: '',
    targetedCompany: false,
    targetedCompanyName: '',
  },
  {
    id: 'cand-003',
    inputDate: '2026-05-21',
    department: 'QC',
    name: 'Le Hoang C',
    email: 'c.le@email.com',
    phone: '0923456789',
    recruiter: 'Tran Lan',
    jobCode: 'IDL-QC-002',
    jobTitle: 'Quality Engineer',
    eeLevel: 'Engineer',
    project: 'Quality Ramp-up',
    hiringManager: 'Le Quang Huy',
    dlIdl: 'IDL',
    status: 'Offered',
    onboardingDate: '',
    offerSentDate: '2026-06-04',
    source: 'Vietnamworks Search',
    employeeId: '',
    referrerName: '',
    referrerDepartment: '',
    note: 'Strong test coverage and audit experience.',
    currentSalary: 25,
    expectedSalary: 32,
    candidateResultFeedbackDate: '2026-06-03',
    headhuntAgency: '',
    targetedCompany: true,
    targetedCompanyName: 'Samsung',
  },
  {
    id: 'cand-004',
    inputDate: '2026-05-25',
    department: 'QC',
    name: 'Pham Kim D',
    email: 'd.pham@email.com',
    phone: '0934567890',
    recruiter: 'Tran Lan',
    jobCode: 'IDL-QC-002',
    jobTitle: 'Quality Engineer',
    eeLevel: 'Engineer',
    project: 'Quality Ramp-up',
    hiringManager: 'Le Quang Huy',
    dlIdl: 'IDL',
    status: 'Offer Accepted',
    onboardingDate: '2026-07-01',
    offerSentDate: '2026-06-01',
    source: 'LinkedIn Job Post',
    employeeId: 'E260701',
    referrerName: '',
    referrerDepartment: '',
    note: 'Accepted. Awaiting onboarding documents.',
    currentSalary: 24,
    expectedSalary: 30,
    candidateResultFeedbackDate: '2026-06-02',
    headhuntAgency: '',
    targetedCompany: false,
    targetedCompanyName: '',
  },
  {
    id: 'cand-005',
    inputDate: '2026-05-29',
    department: 'LOG',
    name: 'Do Minh E',
    email: 'e.do@email.com',
    phone: '0945678901',
    recruiter: 'Nguyen Thuy',
    jobCode: 'IDL-LOG-003',
    jobTitle: 'Logistics Supervisor',
    eeLevel: 'Supervisor',
    project: 'Warehouse Optimization',
    hiringManager: 'Do Thanh Son',
    dlIdl: 'IDL',
    status: 'Searching',
    onboardingDate: '',
    offerSentDate: '',
    source: 'Headhunt',
    employeeId: '',
    referrerName: '',
    referrerDepartment: '',
    note: 'Agency sourcing in progress.',
    currentSalary: 28,
    expectedSalary: 36,
    candidateResultFeedbackDate: '',
    headhuntAgency: 'Navigos',
    targetedCompany: true,
    targetedCompanyName: 'DHL',
  },
  {
    id: 'cand-006',
    inputDate: '2026-06-01',
    department: 'AS',
    name: 'Hoang Tuan F',
    email: 'f.hoang@email.com',
    phone: '0956789012',
    recruiter: 'Tran Lan',
    jobCode: 'IDL-AS-004',
    jobTitle: 'Automation Technician',
    eeLevel: 'Technician',
    project: 'Automation Support',
    hiringManager: 'Vu Duc Long',
    dlIdl: 'IDL',
    status: 'CV Sent',
    onboardingDate: '',
    offerSentDate: '',
    source: 'TopCV Job Post',
    employeeId: '',
    referrerName: '',
    referrerDepartment: '',
    note: 'PLC maintenance experience.',
    currentSalary: 16,
    expectedSalary: 22,
    candidateResultFeedbackDate: '',
    headhuntAgency: '',
    targetedCompany: false,
    targetedCompanyName: '',
  },
];

const includesStatus = (status, validStatuses) => validStatuses.includes(status);

export const calculatePipelineForJob = (jobCode, candidates) => {
  const jobCandidates = candidates.filter((candidate) => candidate.jobCode === jobCode);

  return {
    cvSent: jobCandidates.filter((candidate) => includesStatus(candidate.status, pipelineStatuses.cvSent)).length,
    interview: jobCandidates.filter((candidate) => includesStatus(candidate.status, pipelineStatuses.interview)).length,
    offered: jobCandidates.filter((candidate) => includesStatus(candidate.status, pipelineStatuses.offered)).length,
    offerAccepted: jobCandidates.filter((candidate) => includesStatus(candidate.status, pipelineStatuses.offerAccepted)).length,
    onboarded: jobCandidates.filter((candidate) => includesStatus(candidate.status, pipelineStatuses.onboarded)).length,
    offerRejected: jobCandidates.filter((candidate) => includesStatus(candidate.status, pipelineStatuses.offerRejected)).length,
  };
};

export const hasDuplicateCandidate = (candidate, candidates, excludeId) => {
  const name = candidate.name?.trim().toLowerCase();
  const phone = candidate.phone?.trim();
  const email = candidate.email?.trim().toLowerCase();

  return candidates.some((existing) => {
    if (excludeId && existing.id === excludeId) return false;
    const sameEmail = email && existing.email?.trim().toLowerCase() === email;
    const sameNameAndPhone =
      name && phone && existing.name?.trim().toLowerCase() === name && existing.phone?.trim() === phone;
    return sameEmail || sameNameAndPhone;
  });
};